/* hack01 */

/* 

A super basic hacking simulator I was working on. If anybody has a compiler and gullible friends they  want to trick, go ahead. I just made it because
I was bored. :)

Супер простой симулятор взлома, над которым я работал. Если у кого-то есть компилятор и доверчивые друзья, которых они хотят обмануть, продолжайте. 
я просто сделал это, потому что mне было скучно. )))

*/



#include <iostream>
#include <windows.h>

int main() {

	std::cout << "hack01 Hacker" << std::endl;
	std::cout << "=============" << std::endl << std::endl;
	std::cout << "Prepearing Hack..." << std::endl;
	Sleep(2000);
	std::cout << "Enter target IP: ";
	std::string ip;
	std::cin >> ip;
	std::cout << "Hacking target " << ip << "...";
	Sleep(5000);
	std::cout << "Some memory dump results may appear on the screen. Please be advised..." << std::endl;
	std::cout << "Hacking target..." << std::endl;
	Sleep(5000);
	std::cout << "ZGF0YTpib2FyZC9jb3BpZWRJdGVtcztbIltcIlJhc3RlclwiLHtcImFwcGx5TWF0cml4XCI6ZmFsc2UsXCJtYXRyaXhcIjpbMS4yLDAsMCwxLjIsLTQ0OSwtMjEuNV0sXCJzZWxlY3RlZFwiOnRydWUsXCJkYXRhXCI6e30sXCJjcm9zc09yaWdpblwiOlwiYW5vbnltb3VzXCIsXCJzb3VyY2VcIjpcImh0dHBzOi8vYml0cGFwZXIuczMuYW1hem9uYXdzLmNvbS80Njk5OTkyMTUyOTcwMDg1P2NhY2hlYmxvY2s9dHJ1ZVwiLFwid2lkdGhcIjo3OTcsXCJoZWlnaHRcIjo4MDUsXCJzZWxlY3RlZENvbG9yXCI6WzAsMCwwLDBdfV0iXQoKI2luY2x1ZGUgPGlvc3RyZWFtPgppbnQgbWFpbigpIHsKICAgIHN0ZDo6Y291dCA8PCAiaGFjazAxIiA8PCBzdGQ6OmVuZGw7Cn0KZGF0YTpib2FyZC9jb3BpZWRJdGVtcztbIltcIlJhc3RlclwiLHtcImFwcGx5TWF0cml4XCI6ZmFsc2UsXCJtYXRyaXhcIjpbMS4yLDAsMCwxLjIsLTQ0OSwtMjEuNV0sXCJzZWxlY3RlZFwiOnRydWUsXCJkYXRhXCI6e30sXCJjcm9zc09yaWdpblwiOlwiYW5vbnltb3VzXCIsXCJzb3VyY2VcIjpcImh0dHBzOi8vYml0cGFwZXIuczMuYW1hem9uYXdzLmNvbS80Njk5OTkyMTUyOTcwMDg1P2NhY2hlYmxvY2s9dHJ1ZVwiLFwid2lkdGhcIjo3OTcsXCJoZWlnaHRcIjo4MDUsXCJzZWxlY3RlZENvbG9yXCI6WzAsMCwwLDBdfV0iXQoKI2luY2x1ZGUgPGlvc3RyZWFtPgppbnQgbWFpbigpIHsKICAgIHN0ZDo6Y291dCA8PCAiaGFjazAxIiA8PCBzdGQ6OmVuZGw7Cn0KZGF0YTpib2FyZC9jb3BpZWRJdGVtcztbIltcIlJhc3RlclwiLHtcImFwcGx5TWF0cml4XCI6ZmFsc2UsXCJtYXRyaXhcIjpbMS4yLDAsMCwxLjIsLTQ0OSwtMjEuNV0sXCJzZWxlY3RlZFwiOnRydWUsXCJkYXRhXCI6e30sXCJjcm9zc09yaWdpblwiOlwiYW5vbnltb3VzXCIsXCJzb3VyY2VcIjpcImh0dHBzOi8vYml0cGFwZXIuczMuYW1hem9uYXdzLmNvbS80Njk5OTkyMTUyOTcwMDg1P2NhY2hlYmxvY2s9dHJ1ZVwiLFwid2lkdGhcIjo3OTcsXCJoZWlnaHRcIjo4MDUsXCJzZWxlY3RlZENvbG9yXCI6WzAsMCwwLDBdfV0iXQoKI2luY2x1ZGUgPGlvc3RyZWFtPgppbnQgbWFpbigpIHsKICAgIHN0ZDo6Y291dCA8PCAiaGFjazAxIiA8PCBzdGQ6OmVuZGw7Cn0KZGF0YTpib2FyZC9jb3BpZWRJdGVtcztbIltcIlJhc3RlclwiLHtcImFwcGx5TWF0cml4XCI6ZmFsc2UsXCJtYXRyaXhcIjpbMS4yLDAsMCwxLjIsLTQ0OSwtMjEuNV0sXCJzZWxlY3RlZFwiOnRydWUsXCJkYXRhXCI6e30sXCJjcm9zc09yaWdpblwiOlwiYW5vbnltb3VzXCIsXCJzb3VyY2VcIjpcImh0dHBzOi8vYml0cGFwZXIuczMuYW1hem9uYXdzLmNvbS80Njk5OTkyMTUyOTcwMDg1P2NhY2hlYmxvY2s9dHJ1ZVwiLFwid2lkdGhcIjo3OTcsXCJoZWlnaHRcIjo4MDUsXCJzZWxlY3RlZENvbG9yXCI6WzAsMCwwLDBdfV0iXQoKI2luY2x1ZGUgPGlvc3RyZWFtPgppbnQgbWFpbigpIHsKICAgIHN0ZDo6Y291dCA8PCAiaGFjazAxIiA8PCBzdGQ6OmVuZGw7Cn0K\nZGF0YTpib2FyZC9jb3BpZWRJdGVtcztbIltcIlJhc3RlclwiLHtcImFwcGx5TWF0cml4XCI6ZmFsc2UsXCJtYXRyaXhcIjpbMS4yLDAsMCwxLjIsLTQ0OSwtMjEuNV0sXCJzZWxlY3RlZFwiOnRydWUsXCJkYXRhXCI6e30sXCJjcm9zc09yaWdpblwiOlwiYW5vbnltb3VzXCIsXCJzb3VyY2VcIjpcImh0dHBzOi8vYml0cGFwZXIuczMuYW1hem9uYXdzLmNvbS80Njk5OTkyMTUyOTcwMDg1P2NhY2hlYmxvY2s9dHJ1ZVwiLFwid2lkdGhcIjo3OTcsXCJoZWlnaHRcIjo4MDUsXCJzZWxlY3RlZENvbG9yXCI6WzAsMCwwLDBdfV0iXQoKI2luY2x1ZGUgPGlvc3RyZWFtPgppbnQgbWFpbigpIHsKICAgIHN0ZDo6Y291dCA8PCAiaGFjazAxIiA8PCBzdGQ6OmVuZGw7Cn0KZGF0YTpib2FyZC9jb3BpZWRJdGVtcztbIltcIlJhc3RlclwiLHtcImFwcGx5TWF0cml4XCI6ZmFsc2UsXCJtYXRyaXhcIjpbMS4yLDAsMCwxLjIsLTQ0OSwtMjEuNV0sXCJzZWxlY3RlZFwiOnRydWUsXCJkYXRhXCI6e30sXCJjcm9zc09yaWdpblwiOlwiYW5vbnltb3VzXCIsXCJzb3VyY2VcIjpcImh0dHBzOi8vYml0cGFwZXIuczMuYW1hem9uYXdzLmNvbS80Njk5OTkyMTUyOTcwMDg1P2NhY2hlYmxvY2s9dHJ1ZVwiLFwid2lkdGhcIjo3OTcsXCJoZWlnaHRcIjo4MDUsXCJzZWxlY3RlZENvbG9yXCI6WzAsMCwwLDBdfV0iXQoKI2luY2x1ZGUgPGlvc3RyZWFtPgppbnQgbWFpbigpIHsKICAgIHN0ZDo6Y291dCA8PCAiaGFjazAxIiA8PCBzdGQ6OmVuZGw7Cn0KZGF0YTpib2FyZC9jb3BpZWRJdGVtcztbIltcIlJhc3RlclwiLHtcImFwcGx5TWF0cml4XCI6ZmFsc2UsXCJtYXRyaXhcIjpbMS4yLDAsMCwxLjIsLTQ0OSwtMjEuNV0sXCJzZWxlY3RlZFwiOnRydWUsXCJkYXRhXCI6e30sXCJjcm9zc09yaWdpblwiOlwiYW5vbnltb3VzXCIsXCJzb3VyY2VcIjpcImh0dHBzOi8vYml0cGFwZXIuczMuYW1hem9uYXdzLmNvbS80Njk5OTkyMTUyOTcwMDg1P2NhY2hlYmxvY2s9dHJ1ZVwiLFwid2lkdGhcIjo3OTcsXCJoZWlnaHRcIjo4MDUsXCJzZWxlY3RlZENvbG9yXCI6WzAsMCwwLDBdfV0iXQoKI2luY2x1ZGUgPGlvc3RyZWFtPgppbnQgbWFpbigpIHsKICAgIHN0ZDo6Y291dCA8PCAiaGFjazAxIiA8PCBzdGQ6OmVuZGw7Cn0K\nZGF0YTpib2FyZC9jb3BpZWRJdGVtcztbIltcIlJhc3RlclwiLHtcImFwcGx5TWF0cml4XCI6ZmFsc2UsXCJtYXRyaXhcIjpbMS4yLDAsMCwxLjIsLTQ0OSwtMjEuNV0sXCJzZWxlY3RlZFwiOnRydWUsXCJkYXRhXCI6e30sXCJjcm9zc09yaWdpblwiOlwiYW5vbnltb3VzXCIsXCJzb3VyY2VcIjpcImh0dHBzOi8vYml0cGFwZXIuczMuYW1hem9uYXdzLmNvbS80Njk5OTkyMTUyOTcwMDg1P2NhY2hlYmxvY2s9dHJ1ZVwiLFwid2lkdGhcIjo3OTcsXCJoZWlnaHRcIjo4MDUsXCJzZWxlY3RlZENvbG9yXCI6WzAsMCwwLDBdfV0iXQoKI2luY2x1ZGUgPGlvc3RyZWFtPgppbnQgbWFpbigpIHsKICAgIHN0ZDo6Y291dCA8PCAiaGFjazAxIiA8PCBzdGQ6OmVuZGw7Cn0KZGF0YTpib2FyZC9jb3BpZWRJdGVtcztbIltcIlJhc3RlclwiLHtcImFwcGx5TWF0cml4XCI6ZmFsc2UsXCJtYXRyaXhcIjpbMS4yLDAsMCwxLjIsLTQ0OSwtMjEuNV0sXCJzZWxlY3RlZFwiOnRydWUsXCJkYXRhXCI6e30sXCJjcm9zc09yaWdpblwiOlwiYW5vbnltb3VzXCIsXCJzb3VyY2VcIjpcImh0dHBzOi8vYml0cGFwZXIuczMuYW1hem9uYXdzLmNvbS80Njk5OTkyMTUyOTcwMDg1P2NhY2hlYmxvY2s9dHJ1ZVwiLFwid2lkdGhcIjo3OTcsXCJoZWlnaHRcIjo4MDUsXCJzZWxlY3RlZENvbG9yXCI6WzAsMCwwLDBdfV0iXQoKI2luY2x1ZGUgPGlvc3RyZWFtPgppbnQgbWFpbigpIHsKICAgIHN0ZDo6Y291dCA8PCAiaGFjazAxIiA8PCBzdGQ6OmVuZGw7Cn0KZGF0YTpib2FyZC9jb3BpZWRJdGVtcztbIltcIlJhc3RlclwiLHtcImFwcGx5TWF0cml4XCI6ZmFsc2UsXCJtYXRyaXhcIjpbMS4yLDAsMCwxLjIsLTQ0OSwtMjEuNV0sXCJzZWxlY3RlZFwiOnRydWUsXCJkYXRhXCI6e30sXCJjcm9zc09yaWdpblwiOlwiYW5vbnltb3VzXCIsXCJzb3VyY2VcIjpcImh0dHBzOi8vYml0cGFwZXIuczMuYW1hem9uYXdzLmNvbS80Njk5OTkyMTUyOTcwMDg1P2NhY2hlYmxvY2s9dHJ1ZVwiLFwid2lkdGhcIjo3OTcsXCJoZWlnaHRcIjo4MDUsXCJzZWxlY3RlZENvbG9yXCI6WzAsMCwwLDBdfV0iXQoKI2luY2x1ZGUgPGlvc3RyZWFtPgppbnQgbWFpbigpIHsKICAgIHN0ZDo6Y291dCA8PCAiaGFjazAxIiA8PCBzdGQ6OmVuZGw7Cn0K\nZGF0YTpib2FyZC9jb3BpZWRJdGVtcztbIltcIlJhc3RlclwiLHtcImFwcGx5TWF0cml4XCI6ZmFsc2UsXCJtYXRyaXhcIjpbMS4yLDAsMCwxLjIsLTQ0OSwtMjEuNV0sXCJzZWxlY3RlZFwiOnRydWUsXCJkYXRhXCI6e30sXCJjcm9zc09yaWdpblwiOlwiYW5vbnltb3VzXCIsXCJzb3VyY2VcIjpcImh0dHBzOi8vYml0cGFwZXIuczMuYW1hem9uYXdzLmNvbS80Njk5OTkyMTUyOTcwMDg1P2NhY2hlYmxvY2s9dHJ1ZVwiLFwid2lkdGhcIjo3OTcsXCJoZWlnaHRcIjo4MDUsXCJzZWxlY3RlZENvbG9yXCI6WzAsMCwwLDBdfV0iXQoKI2luY2x1ZGUgPGlvc3RyZWFtPgppbnQgbWFpbigpIHsKICAgIHN0ZDo6Y291dCA8PCAiaGFjazAxIiA8PCBzdGQ6OmVuZGw7Cn0KZGF0YTpib2FyZC9jb3BpZWRJdGVtcztbIltcIlJhc3RlclwiLHtcImFwcGx5TWF0cml4XCI6ZmFsc2UsXCJtYXRyaXhcIjpbMS4yLDAsMCwxLjIsLTQ0OSwtMjEuNV0sXCJzZWxlY3RlZFwiOnRydWUsXCJkYXRhXCI6e30sXCJjcm9zc09yaWdpblwiOlwiYW5vbnltb3VzXCIsXCJzb3VyY2VcIjpcImh0dHBzOi8vYml0cGFwZXIuczMuYW1hem9uYXdzLmNvbS80Njk5OTkyMTUyOTcwMDg1P2NhY2hlYmxvY2s9dHJ1ZVwiLFwid2lkdGhcIjo3OTcsXCJoZWlnaHRcIjo4MDUsXCJzZWxlY3RlZENvbG9yXCI6WzAsMCwwLDBdfV0iXQoKI2luY2x1ZGUgPGlvc3RyZWFtPgppbnQgbWFpbigpIHsKICAgIHN0ZDo6Y291dCA8PCAiaGFjazAxIiA8PCBzdGQ6OmVuZGw7Cn0KZGF0YTpib2FyZC9jb3BpZWRJdGVtcztbIltcIlJhc3RlclwiLHtcImFwcGx5TWF0cml4XCI6ZmFsc2UsXCJtYXRyaXhcIjpbMS4yLDAsMCwxLjIsLTQ0OSwtMjEuNV0sXCJzZWxlY3RlZFwiOnRydWUsXCJkYXRhXCI6e30sXCJjcm9zc09yaWdpblwiOlwiYW5vbnltb3VzXCIsXCJzb3VyY2VcIjpcImh0dHBzOi8vYml0cGFwZXIuczMuYW1hem9uYXdzLmNvbS80Njk5OTkyMTUyOTcwMDg1P2NhY2hlYmxvY2s9dHJ1ZVwiLFwid2lkdGhcIjo3OTcsXCJoZWlnaHRcIjo4MDUsXCJzZWxlY3RlZENvbG9yXCI6WzAsMCwwLDBdfV0iXQoKI2luY2x1ZGUgPGlvc3RyZWFtPgppbnQgbWFpbigpIHsKICAgIHN0ZDo6Y291dCA8PCAiaGFjazAxIiA8PCBzdGQ6OmVuZGw7Cn0K\n";
	Sleep(5000);
	std::cout << "\nTarget hacked." << std::endl;
	std::cout << "=======================" << std::endl;
	std::cout << "Username: ADMIN" << std::endl;
	std::cout << "Password: *************" << std::endl;
	std::cout << "Username: User" << std::endl;
	std::cout << "Password: *****" << std::endl;
	std::cout << "Username: BackupAdmin" << std::endl;
	std::cout << "Password: ****************" << std::endl;
	system("pause");
	system("exit");
}
